unit TestDML;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, FileBasedTest;

type

  _Select = class(TFileBasedTest)
  published
    procedure Простейший_Запрос;
    procedure Запрос_С_With;
    procedure Запрос_С_Алиасом;
    procedure Запрос_С_Несколькими_Полями;
    procedure Запрос_С_Алиасами_В_Полях;
    procedure Запрос_С_Выражениями_В_Полях;
    procedure Запрос_С_Выражениями_И_Алиасами;
    procedure Запрос_С_Into;
    procedure Запрос_С_Bulk_Collect_Into;
    procedure Запрос_Из_Нескольких_Таблиц;
    procedure Запрос_Из_Табличной_Функции;
    procedure Запрос_Из_Подзапроса;
  end;

  _Insert = class(TTestCase)
  end;

  _Update = class(TTestCase)
  end;

  _Delete = class(TTestCase)
  end;

  _Merge = class(TTestCase)
  end;

implementation

{ _Select }

procedure _Select.Простейший_Запрос;
begin
end;

procedure _Select.Запрос_С_With;
begin
end;

procedure _Select.Запрос_С_Алиасом;
begin
end;

procedure _Select.Запрос_С_Несколькими_Полями;
begin
end;

procedure _Select.Запрос_С_Алиасами_В_Полях;
begin
end;

procedure _Select.Запрос_С_Выражениями_В_Полях;
begin
end;

procedure _Select.Запрос_С_Выражениями_И_Алиасами;
begin
end;

procedure _Select.Запрос_С_Into;
begin
end;

procedure _Select.Запрос_Из_Нескольких_Таблиц;
begin
end;

procedure _Select.Запрос_Из_Подзапроса;
begin
end;

procedure _Select.Запрос_Из_Табличной_Функции;
begin
end;

procedure _Select.Запрос_С_Bulk_Collect_Into;
begin
end;

initialization
  RegisterTest(_Select.Suite);
  RegisterTest(_Insert.Suite);
  RegisterTest(_Update.Suite);
  RegisterTest(_Delete.Suite);
  RegisterTest(_Merge.Suite);
end.


